### ISSUE TITLE
</ characters are displayed wrongly (maybe for some sort of native ligature)

### ISSUE THREAD

**Issue by pasqualedante** [googlefonts/spacemono#8]
The char < and the char / get a weird effect, as show in the attached screenshot
<img width="668" alt="rr" src="https://user-images.githubusercontent.com/813690/55290725-ffba0a80-53d6-11e9-8d4d-85197e3af9e2.png">

**Comment by pasqualedante** [comment]
Sorry I've seen that the glyph is really a native gliph, then this is by design. Sorry for the mistake.

**Comment by MrJmpl3** [comment]
> 
> 
> Sorry I've seen that the glyph is really a native gliph, then this is by design. Sorry for the mistake.

How to fix?
